CLASS zcl_09_itab_angelo DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_09_itab_angelo IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.

**********Concepts

    ""EN SU MAYORIA LAS TABLAS INTERNAS EN ABAP, SON USADAS PARA LA OPERACION Y PROCESAMIENTO DE LOS DATOS. LAS TABLAS INTERNAS EXISTEN SOLAMENTE CUANDO EL PROGRAMA
    ""SE ESTA EJECUTANDO. AL TRABAJAR CON ELLAS PODEMOS NOTAR QUE SE COMPORTAN DE LAS MISMA MANERA QUE LAS ESTRUCTURAS, LAS QUE CONOCEMOS TAMBIEN COMO AREAS DE TRABAJO
    ""ESTAS RECORDEMOS QUE CUENTAN CON SOLO UN REGISTRO. MINETRAS QUE LAS TABLAS INTERNAS PUEDEN CONTENER N LINEAS COMO UNA TABLA DE BASE DE DATOS NORMAL, PERO NO PODEMOS
    ""CONFUNDIR LOS CONCEPTOS DE UNA TABAL INTERNA Y UNA DE BASE DE DATOS, LAS TABLAS INTERNAS SON FELXIBLES YA QUE PUDEN SER CREADAS USANDO OTRAS ESTRUCTURS DEFINIDAS
    ""PARA LLEGAR A TENER MUCHAS ESTRUCTURAS DE TABLAS NORMALES, AGRUPADAS Y PUESTAS A UNA TABLA INTERNA. OTRA COSA IMPORTANTE DE CONOCER ES: QUE TODAS LA ENTRADAS DE UNA
    ""TABLA INTERNA, DEBEN TENER LA MISMA ESTRUCTURA. PODMEOS ACCEDER A UNA LINEA MEDIANTE UNA CLAVE O UN INDICE. LAS TABLAS INTERNAS SON MEMORIA DINAMICA, ES DECIR,
    ""SE CREAN EN TIEMPO DE EJECUCION DEL PROGRAMA, EN LA PARTE DE LA MEMORIA RAM ASIGNADA A ESTE PROPOSITO Y DESAPARECEN UNA VESZ QUE SE HA EJECUTADO EL BLOQUE
    ""POR EL QUE SE HABIA CREADO

**********INTERNAL TABLE TYPES

*****STANDARD TABLE

    ""ESTE ES EL TIPO DE TABLA QUE SE CREA POR DEFECTO SI NO SE ESPECIFICA EL TYPE EN EL MOMENTO DE LA DECLARACION. LAS LINEAS DE ESTE TIPO DE TABLA ESTAN ORGANIZADAS
    ""SEGUN UN INDICE, ESTE INDICE ES INTERNO Y PARA BUSCAR UN REGISTRO DETERMINADO DE LA TABLA, SE PUDE HACER MEDIANTE UN INDICE PRINCIPALMENTE O MEDIANTE UNA CLAVE
    ""PERO SU BUSQUEDA PRINCIPAL ES CON INDICE Y EL TIPO DE ACCESO QUE SE USA ES LINEAL, ES DECIR, IR REGISTRO POR REGISTRO HASTA ENCONTRAR EL DESEADO O HASTA ENCONTRAR
    ""EL REGISTRO DONDE ESTAMOS O QUEREMOS HACER LA OPERACION. ESTE TIPO DE TABLA OCUPA MENOS MEMORIA Y SE LE PUEDEN AÑADIR REGISTROS MUY RAPIDAMENTE, PERO ES POCO
    ""EFICIENTE SI NECESITAMOS BUSCAR REGISTROS CON FRECUENCIA, SOBRE TODO SI LA BASE DE DATOS TIENE MUCHAS ENTRADAS. EL TIEMPO DE BUSQUEDA SE INCREMANETA LINEALMENTE
    ""CON EL NUMERO DE REGISTROS. SOLO DEBEN UTILIZARCE EN LOS SIGUENTES CASO: 1- CUANDO LAS TABLAS SON PEQUEÑAS O POCAS ENTRADAS, DONDE LA INXSACION ES FAVORABLE
    ""Y EL PROCESAMIENTO NO PRODUCIRA UNA SOBRECARGA 2-CUANDO SON TABLAS TIPO ARRAY EN LAS QUE EL ORDEN DE LAS ENTRADAS NO IMPORTA O EN EL QUE LAS ENTRADAS PUEDEN
    ""PROCESARSE EN EL ORDEN EXACTO EN EL QUE SE INGRESARON.

*****SORTED TABLE O TABLAS ORDENADAS

    ""LAS LINEAS DE ESTE TIPO DE TABLAS TIENE ASIGNADAS UN INDICE INTERNO, APARECERAN ORDENASDAS DE ACUERDO CON LLA CLAVE QUE PUDE SER UNICA O NO UNICA Y EL ACCESO SE
    ""REALIZA ATRAVES DE LA CLAVE PRINCIPALMENTE. EL ALGORTIMO DE BUSQUEDA ES BINARIO Y EN TIEMPO DE BUISQUEDA SE INCREMENTA DE FORMA LOGARITMICA A MEDIDA QUE SE
    ""AÑADEN MAS REGISTROS A LA TABLA. ESTAS MEJORAN LA EFICIENCIA GLOBAL DENTRO DEL CODIGO CUANDO SE ESPERA UN GRAN NUMERO DE ACCESO A FILAS, YA QUE, LA BUSQUEDA
    ""BINARIA SE LLEVA AUTOMATICAMENTE DURANTE LOS ACCESOS.

*****HASHED TABLE

    ""EN ESTAS TABLAS NO SE PUEDE ACCEDER MEDIANTE EL INDICE Y EL ORDEN DE LOS REGISTROS QUE SE AÑADEN A DICHA TABLA, SE REALIZAN ATRAVES DE UN ALGORTIMO NUMERICO
    ""LLAMDO "HASHED FUNCTION", EL CUAL CALCULA LA POSICION DE UN REGISTRO PARTIENDO DE UNA DETERMINADA CLAVE Y LA CLAVE DE ESTA TABLA ES UNICA. EL TIEMPO DE
    ""ACCESOA UN  DETERMINADO REGISTRO ES CONSTANTE, INDEPENDIENTEMENTE DEL NUMERO DE ENTRADAS QUE TENGA LA BASE DE DATOS Y ES SIEMPRE MENOR QUE LOS OTROS
    ""TIPOS DE TABLAS INTERNA, TAN SOLO DEPENDE DEL ALGORITMO Y LA RAPIDEZ DEL SISTEMA, Y SUELE SER MUY PEQUEÑO ESTE TIEMPO, ESTE TIPO DE TABLA ES EL MAS ADECUADO
    ""SI LA ACCION MAS FRECUENTE ES ACCEDER A UNA LINEA POR LA CLAVE, ESTO SERA ASI CUANDO POR EJMPLO SE QUIERA CREAR UNA TABLA INTERNA QUE SE PAREZCA UNA TABLA DE
    ""BASE DE DATO, TAMBIEN ES EL ADECUADO SI DEASEAMOS PROCESAR GRANDES CANTIDADES DE DATOS. NO VALEN LA PENA PARA TABLAS PEQUEÑAS CUYAS ENTRADAS PUEDEN SER
    ""ACCEDIDAS FACILMENTE POR EN INDICE, EN ESE CASO SERIA MEJOR USAR UNA STANDARD.

**********INTERNAL TABLE DECLARATIONS

*****STANDARD TABLE

    DATA lt_flight_stand TYPE STANDARD TABLE OF /dmo/flight.
    DATA lt_flight_stand2 TYPE TABLE OF /dmo/flight. ""TABMIEN SE PUEDE DECLARAR UNA STANDARD SIN PONER LA PALABRA STANDARD

*****SORTED TABLE

    DATA lt_flight_sort TYPE SORTED TABLE OF /dmo/flight WITH NON-UNIQUE KEY carrier_id. ""ESTA PUDEN TENER CLAVE NON-UNIQUE O UNIQUE Y EN CASO DE TENER LA CLAVE UNIQUE,
                                                                                         ""NO SE PUDE TENER MAS DE UN REGISTRO CON LA MISMA CLAVE Y EL NON-UNIQUE QUIERE DECIR QUE PODMEOS TENER LA MISMA CLAVE

*****HASHED TABLE

    DATA lt_flight_hashed TYPE HASHED TABLE OF /dmo/flight WITH UNIQUE KEY carrier_id.















  ENDMETHOD.



ENDCLASS.
